2025-02-28 11:02 ERROR Traceback (most recent call last):
  File "/home/b0457812963/RL_mamba/SynapseX/Major/DataProvider.py", line 91, in reload_all_data
    original_df, eachCatchDf = self.reload_data(
                               ^^^^^^^^^^^^^^^^^
  File "/home/b0457812963/RL_mamba/SynapseX/Major/DataProvider.py", line 62, in reload_data
    original_df, eachCatchDf = self.Binanceapp.BinanceData.download(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b0457812963/RL_mamba/SynapseX/Major/custom.py", line 43, in wrapper
    result = func(self, client, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b0457812963/RL_mamba/SynapseX/Major/custom.py", line 269, in download
    klines = cls.historicalklines(symbol, kline_size, oldest_point.strftime("%d %b %Y %H:%M:%S"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b0457812963/RL_mamba/SynapseX/Major/custom.py", line 126, in historicalklines
    temp_data = client._klines(
                ^^^^^^^^^^^^^^^
  File "/home/b0457812963/RL_mamba/lib/python3.12/site-packages/binance/client.py", line 712, in _klines
    return self.futures_klines(**params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b0457812963/RL_mamba/lib/python3.12/site-packages/binance/client.py", line 7115, in futures_klines
    return self._request_futures_api("get", "klines", data=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b0457812963/RL_mamba/lib/python3.12/site-packages/binance/client.py", line 122, in _request_futures_api
    return self._request(method, uri, signed, force_params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b0457812963/RL_mamba/lib/python3.12/site-packages/binance/client.py", line 88, in _request
    self.response = getattr(self.session, method)(uri, headers=headers, data=data, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b0457812963/RL_mamba/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b0457812963/RL_mamba/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b0457812963/RL_mamba/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b0457812963/RL_mamba/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/b0457812963/RL_mamba/lib/python3.12/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/b0457812963/RL_mamba/lib/python3.12/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/b0457812963/RL_mamba/lib/python3.12/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1252, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1104, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

2025-02-28 11:02 ERROR symbol = MAVUSDT
