2025-02-05 00:58 ERROR Traceback (most recent call last):
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\TradingSysteam.py", line 317, in main
    self.dataprovider.Binanceapp.execute_orders(
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 58, in wrapper
    result = func(self, client, *new_args, **new_kwargs)
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 488, in execute_orders
    leverage = int(position[0]['leverage'])
KeyError: 'leverage'

2025-02-05 00:58 ERROR CANCEL read_loop
2025-02-05 01:03 ERROR Traceback (most recent call last):
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\TradingSysteam.py", line 317, in main
    self.dataprovider.Binanceapp.execute_orders(
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 58, in wrapper
    result = func(self, client, *new_args, **new_kwargs)
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 489, in execute_orders
    leverage = int(position[0]['leverage'])
KeyError: 'leverage'

2025-02-05 01:03 ERROR Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001D4EF2E62C0>
2025-02-05 01:14 ERROR Traceback (most recent call last):
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\TradingSysteam.py", line 317, in main
    self.dataprovider.Binanceapp.execute_orders(
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 58, in wrapper
    result = func(self, client, *new_args, **new_kwargs)
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 491, in execute_orders
    leverage = int(position[0]['leverage'])
KeyError: 'leverage'

2025-02-05 01:14 ERROR Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000029728B20EB0>
2025-02-05 01:20 ERROR Traceback (most recent call last):
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\TradingSysteam.py", line 317, in main
    self.dataprovider.Binanceapp.execute_orders(
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 58, in wrapper
    result = func(self, client, *new_args, **new_kwargs)
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 496, in execute_orders
    leverage = int(position[0]['leverage'])
KeyError: 'leverage'

2025-02-05 01:20 ERROR Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000269CD4A60E0>
2025-02-05 01:28 ERROR Traceback (most recent call last):
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\TradingSysteam.py", line 317, in main
    self.dataprovider.Binanceapp.execute_orders(
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 58, in wrapper
    result = func(self, client, *new_args, **new_kwargs)
  File "c:\Users\a046829713\Desktop\program\RLTrading\SynapseX\Major\custom.py", line 496, in execute_orders
    leverage = int(position[0]['leverage'])
KeyError: 'leverage'

2025-02-05 01:28 ERROR Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000021EF6D1BA30>
